port: 2355
save_video: true
seed: 0

PipelineParams:
  convert_SHs_python: False #true = using direct rgb
ModelParams:
  workspace: 
  sh_degree: 0
  bg_aug_ratio: 0.66

GuidanceParams:
  LCM_model_key: 'lykon/dreamshaper-7'
  LCM_LoRA_key: 'latent-consistency/lcm-lora-sdv1-5'
  controlnet_depth_model_key: 'lllyasviel/sd-controlnet-depth'
  text: 'a plush dragon toy'
  negative: 'blurry, low quality, out of focus, ugly, unrealistic, low contrast, dull, low-resolution, oversaturation.'
  inverse_text: ''
  perpneg: True
  C_batch_size: 4
  t_range: [0.6, 0.7]
  max_t_range: 0.7
  t_range_2: [0.2, 0.5]
  lambda_guidance: 0.1
  guidance_scale: 7.5
  guidance_scale2: 5
  denoise_guidance_scale: 1.0
  noise_seed: 0

  ddim_inv: true
  annealing_intervals: true

  xs_delta_t: 200
  xs_inv_steps: 4
  xs_inv_steps_range: [2, 3]
  xs_eta: 0.0
  
  delta_t: 80
  delta_t_start: 100

  is_LCM: True
  LCM_LoRA: True

  vis_interval: 50

  x0_iters: 1000
  timestep_ratio1: True
  timestep_ratio2: True
  x0_loss: True
  sds: true
  add_noise_multi_steps: true
  LCM_steps_num_range1: [1, 1]
  LCM_steps_num_range: [2, 2]
  resolution_warm_up: True
  
  agg_first: True
  first_stage_DDIM: False

GenerateCamParams:
  init_shape: 'pointe_finetune'
  init_prompt: 'a dragon.'  
  use_pointe_rgb: false
  init_num_pts: 100_000
  phi_range: [-180, 180]
  max_phi_range: [-180, 180]
  rand_cam_gamma: 1.5

  theta_range: [45, 90]
  max_theta_range: [45, 90]

  radius_range: [5.2, 5.5] #[3.8, 4.5] #[3.0, 3.5]
  max_radius_range: [3.5, 5.0] #[3.8, 4.5] #[3.0, 3.5]
  default_radius: 3.5
 
  default_fovy: 0.55
  fovy_range: [0.32, 0.60]
  max_fovy_range: [0.16, 0.60]

OptimizationParams:
  iterations: 4500     # 5000
  save_process: True
  pro_frames_num: 500
  pro_render_45: False
  warmup_iter: 1500 # 2500

  as_latent_ratio : 0.2
  geo_iter : 0
  densify_from_iter: 100
  densify_until_iter: 3000
  densification_interval: 100   # 稠密化间隔
  percent_dense: 0.003
  densify_grad_threshold: 0.00075
  progressive_view_iter: 500 #1500
  opacity_reset_interval: 300 #500

  scale_up_cameras_iter: 500
  fovy_scale_up_factor: [0.75, 1.1]
  phi_scale_up_factor: 1.5

  position_lr_init: 0.0002
  position_lr_final: 0.0000016
  # position_lr_delay_mult: 0.3
  # position_lr_delay_steps: 800
  feature_lr: 0.005
  feature_lr_final: 0.003
  # opacity_lr: 0.01
  scaling_lr: 0.005
  scaling_lr_final: 0.001
  # rotation_lr: 0.001
  # rotation_lr_final: 0.001
  # densify_from_iter: 500
  # densify_until_iter: 15000
  # percent_dense: 0.004
  # densify_grad_threshold: 0.0002
  # densification_interval: 100   # 稠密化间隔
  # opacity_reset_interval: 3000
  lambda_tv: 1
  lambda_scale: 0

  lr_warmup_steps: 70
  lr_warmup_factor: 0.1
